// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaixorkooivyhnmxbqrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhaXhvcmtvb2l2eWhubXhicXJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0Mzg2MzQsImV4cCI6MjA2NTAxNDYzNH0.rOG-pRNNCRFPKC1KB7aE6rZuBxqWjRUElhJTtrpBiXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);